### PR TITLE
fix #121 fix #56 

### LINKED ISSUE #56: Intervening elements are re-rendered if an element is added both before and after them
This example might explain better
```
include karax / prelude
import future
var page = 1

proc createDom(): VNode = buildHtml(tdiv):
  h1:
    text "Testing"
  if page == 3 or page == 4:
    tdiv: text "Some text"
  input(`type`="text")
  button(onclick=() => (page = 1)): text "1"
  button(onclick=() => (page = 2)): text "2"
  button(onclick=() => (page = 3)): text "3"
  button(onclick=() => (page = 4)): text "4"
  if page == 2 or page == 4:
    tdiv: text "Some text"
setRenderer createDom
```

Going from page 1 to page 2 or page 1 to page 3 works as expected. But page 1 to page 4 causes the input and buttons 1, 2 and 3 to be re-rendered.

### LINKED ISSUE #121: regression: Failed to execute 'replaceChild' on 'Node' when using `dthunk`
```
karun -r main.nim
open page in browser
click on button
```
in console log, shows: 
```
Uncaught DOMException: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
    at apply_patch_526222 (file:///Users/timothee/git_clone/nim/timn/nimcache/main.js:2486:24)
    at dodraw_529246 (file:///Users/timothee/git_clone/nim/timn/nimcache/main.js:2618:3)
    at HEX3Aanonymous_530601 (file:///Users/timothee/git_clone/nim/timn/nimcache/main.js:2671:5)
```
and the output html is wrong:
```
Temp
0 txt:2
1 txt:3
2 # should not be here
3 # should not be here
4 txt:4
```

reduced example:
```nim
import karax / [kbase, vdom, kdom, karax, karaxdsl]
import std/jsffi

var velements: seq[Node]
for i in 0..<5: # s/5/4 would work
  let v = document.createTextNode("txt:" & $i)
  # v.id = "id:" & $i # doesn't help
  velements.add v

proc createDom*(): VNode =
  result = buildHtml(tdiv):
    button():
      text "Temp"
      proc onclick() =
        velements = velements[2..^1]
    for i, v in velements:
      tdiv:
        text $i & " "
        dthunk(v)

when isMainModule:
  setRenderer createDom, "ROOT"
```

## note
marking as regression because before e422087 (exponential dom diffing) it wasn't throwing `replaceChild` error; however it's only a half-regression as the output was not correct, showing:
```
0 txt:0
1 txt:1
2 txt:2
```
instead of:
```
0 txt:2
1 txt:3
2 txt:4
```

## note
weirdly, `0..<4` would not result in bug, unlike `0..<5`

/cc @araq this bug is a blocker; unlike https://github.com/pragmagic/karax/issues/56 (where I could add a unique id), I don't know of a workaround

### PR DESCRIPTION
**Pull request by timotheecour**
/cc @araq this seems to:
* fix #121 (as well as my original problem from which this was a reduced case)
also works with reordering eg: `velements = velements[2..^1]` => `velements = @[velements[2], velements[4], velements[3]]`
* fix #56 (in particular https://github.com/pragmagic/karax/issues/56#issuecomment-531099826 which more obviously exhibits the bug)

### CODE REVIEW

File: karax/karax.nim [hunk 1]
```diff
@@ -376,7 +376,10 @@ proc applyPatch(kxi: KaraxInstance) =
       if p.parent == nil:
         replaceById(kxi.rootId, nn)
       else:
-        p.parent.replaceChild(nn, p.current)
+        if p.current.parentNode == p.parent:
+          p.parent.replaceChild(nn, p.current)
+        else: # fix #121
+          p.parent.appendChild(nn)
```
Comment (Araq) [inline karax/karax.nim]: Well that's a workaround. The patch enum clearly says ``pkReplace``.

**Comment by Araq** [comment]
But it does improve the situation, so merging.

File: karax/karax.nim (hunk 1 above)
Comment (timotheecour) [reply karax/karax.nim]: right; what may be going on here is that the parent of p.current is not what we'd expect because of a prior node relocation (via replaceChild)
